### PR TITLE
list number of flatpak packages, if flatpak is present

### PR DESCRIPTION
**Pull request by Lunarequest**
I've added a section in packages to list the number of packages installed via flatpak if present

### CODE REVIEW

**Comment by curlpipe** [comment]
Surely there's a cleaner way to do this? 

Why not just add

```rust
        if let Ok(n) = run_fun!(flatpak list | wc -l) {
            out.push_str(&format!("{} (flatpak)", n))
        }
```

This code pushes the package count text to `out` if available, no need to add individual cases for each, which gets messy quickly.

This would make the `get_packages` function look like this:

```rust
    pub fn get_packages() -> Option<String> {
        let mut out = String::new();
        if let Ok(n) = run_fun!(xbps-query -l | wc -l) {
            out.push_str(&format!("{} (xbps)", n))
        }
        if let Ok(n) = run_fun!(pacman -Q | wc -l) {
            out.push_str(&format!("{} (pacman)", n))
        }
        if let Ok(n) = run_fun!(flatpak list | wc -l) {
            out.push_str(&format!("{} (flatpak)", n))
        }
        Some(out)
    }
```

Might need some spaces to delimit each package counter text though

**Comment by Lunarequest** [comment]
Yeah I'll add this

**Comment by Lunarequest** [comment]
we can just add a delimit to the flatpaks part since its impossible  to have a system with only flatpaks.

**Comment by curlpipe** [comment]
Thanks for the contribution!

**Pull request merged**
